# Generated by Django 4.0.4 on 2022-05-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_forgotpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgotpassword',
            old_name='user_date',
            new_name='used_at',
        ),
    ]
