# Generated by Django 4.0.4 on 2022-05-17 13:18

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_user_date_forgotpassword_used_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpassword',
            name='expire_at',
            field=models.DateTimeField(blank=True, default=student.models.expire_time, null=True),
        ),
    ]
